/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proj2;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public String createMessage() {
        return "message from proj2";
    }
}
